import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/homepage/header/navbar";
import Footer from "./components/homepage/footer/page";

const poppins = Poppins({ subsets: ["latin"], weight: "400", display: "swap" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
